package pubstatemachine.message;

public enum MessageType {
  COMMAND_GRAPHIC_EDIT,
  COMMAND_COPY_EDIT,
  COMMAND_PUBLISH,
  EVENT_PUBLISHED,
  EVENT_EDITABLE,
  EVENT_PUBLISHABLE,
  EVENT_AWAIT_COPY_EDIT,
  EVENT_AWAIT_GRAPHIC_EDIT,
}
